GH #13: adding sanity tests for generated files since we cannot trust the exit code of rails generators to be non-zero on failure

diff --git a/script/ci b/script/ci
--- a/script/ci
+++ b/script/ci
@@ -1,17 +1,21 @@
-#!/bin/bash -v
+#!/bin/bash
 
 RAILS_APP="app_for_ci"
 TARGET_HOST="placeholder.example.com"
 
+# Setup RVM
 source "$HOME/.rvm/scripts/rvm"
-rvm use "ruby-1.9.2@relevance_rails"
+rvm gemset use "relevance_rails"
+
+echo "DEBUG: using gemset: `rvm gemset name`"
+
+# exit if any statement fails; 
+# must be set AFTER loading RVM
+set -e
 
 gem install bundler
 bundle install
 bundle exec rake spec
-
-# exit if any statement fails; must be set AFTER loading RVM
-set -e
 
 echo "Building new relevance_rails gem..."
 rm -Rf relevance_rails-*.gem
@@ -43,15 +47,43 @@ relevance_rails new $RAILS_APP --database=postgresql
 # NOTE: this does NOT change the RVM gemset; we set it manually above
 builtin cd $RAILS_APP
 
+for checked_file in public/index.html; do
+  if [ -e $checked_file ]; then
+    echo "$checked_file still exists!"
+    exit 1
+  fi
+done
+
+for checked_file in config/database.yml provision/dna.json config/deploy.rb config/deploy/recipes/deploy.rb; do
+  if [ ! -e $checked_file ]; then
+    echo "$checked_file didn't exist!"
+    exit 1
+  fi
+done
+
 echo "Generating relevance_rails deployment scripts..."
 ./script/rails generate deployment staging $TARGET_HOST
 git add .
 git commit -m "Generated relevance_rails deployment scripts."
 echo "Done."
 
+for checked_file in config/deploy/staging.rb; do
+  if [ ! -e $checked_file ]; then
+    echo "$checked_file didn't exist!"
+    exit 1
+  fi
+done
+
 echo "Generating relevance_rails fixtures..."
 ./script/rails generate fixtures
 git add .
 git commit -m "Generated relevance_rails fixtures."
 echo "Done."
+
+for checked_file in app/assets/javascripts/relevance_rails.js.coffee app/assets/stylesheets/relevance_rails.css.scss; do
+  if [ ! -e $checked_file ]; then
+    echo "$checked_file didn't exist!"
+    exit 1
+  fi
+done
 
