GH #22: always fail if command fails, even if we don't have an active EC2 instance

diff --git a/script/ci_nightly b/script/ci_nightly
--- a/script/ci_nightly
+++ b/script/ci_nightly
@@ -8,8 +8,10 @@ function stop_server_and_exit {
     echo "Stopping newly-created server..."
     bundle exec rake provision:stop FORCE=true --trace
     echo "Done."
-    exit 1
   fi  
+
+  echo "BUILD FAILED"
+  exit 1
 }
 
 echo "RVM is now using:` rvm current`"
